[package]
name = "astria-test-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "2.0.7", features = ["ws"], optional = true }
impl-serde = { version = "0.4.0", optional = true }
jsonrpsee = { workspace = true, optional = true, features = ["macros", "server"] }
rand = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
tokio-test = { workspace = true }

[features]
geth = [
  "dep:ethers",
  "dep:impl-serde",
  "dep:jsonrpsee",
  "dep:rand",
  "dep:tokio",
  "tokio/rt",
  "dep:tracing",
]
