[package]
name = "astria-test-utils"
version = "0.1.0"
edition = "2021"
rust-version = "1.71.1"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/astriaorg/astria"
homepage = "https://astria.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
impl-serde = { version = "0.4.0", optional = true }
ethers = { workspace = true, features = ["ws"], optional = true }
jsonrpsee = { workspace = true, optional = true, features = [
  "macros",
  "server",
] }
rand = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
tokio-test = { workspace = true }

[features]
geth = [
  "dep:ethers",
  "dep:impl-serde",
  "dep:jsonrpsee",
  "dep:rand",
  "dep:tokio",
  "tokio/rt",
  "dep:tracing",
]
