newline_style = "Unix"
wrap_comments = true
format_code_in_doc_comments = true
comment_width = 100
normalize_comments = true
format_strings = true
format_macro_matchers = true
struct_lit_single_line = false
imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_impl_items = true
edition = "2021"
version = "Two"
use_field_init_shorthand = true
condense_wildcard_suffixes = true
unstable_features = true
