[package]
name = "astria-sequencer-relayer"
version = "0.9.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.73"

[dependencies]
dirs = "5.0"
http = "0.2.9"
serde_path_to_error = "0.1.13"
zeroize = { version = "1.6.0", features = ["zeroize_derive"] }

axum = { workspace = true }
backon = { workspace = true }
base64 = { workspace = true }
base64-serde = { workspace = true }
ed25519-consensus = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
hex = { workspace = true, features = ["serde"] }
humantime = { workspace = true }
hyper = { workspace = true }
prost = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tendermint = { workspace = true, features = ["rust-crypto"] }
tendermint-config = { workspace = true }
tendermint-rpc = { workspace = true, features = ["http-client"] }
tracing = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

celestia-client = { package = "astria-celestia-client", path = "../celestia-client" }
config = { package = "astria-config", path = "../config" }
proto = { package = "astria-proto", path = "../proto" }
sequencer-client = { package = "astria-sequencer-client", path = "../sequencer-client", features = [
  "http",
] }
telemetry = { package = "astria-telemetry", path = "../telemetry" }

[dev-dependencies]
celestia-mock = { package = "astria-celestia-mock", path = "../celestia-mock" }
config = { package = "astria-config", path = "../config", features = [
  "tests",
] }
merkle = { package = "astria-merkle", path = "../merkle" }
sequencer-types = { package = "astria-sequencer-types", path = "../sequencer-types", features = [
  "test-utils",
] }

rand_core = { version = "0.6", features = ["getrandom"] }

jsonrpsee = { workspace = true, features = ["server"] }
once_cell = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
wiremock = { workspace = true }
