[package]
name = "astria-proto"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/astriaorg/astria"
homepage = "https://astria.org"
# TODO
# documentation = ""

categories = ["astria-proto", "astria-rpc", "rpc-types"]
keywords = ["astria", "grpc", "rpc", "blockchain", "execution", "protobuf"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-consensus = "2.1.0"
hex.workspace = true
prost = { workspace = true }
prost-types = { workspace = true }
sha2.workspace = true
tendermint-proto = { workspace = true }
tonic = { workspace = true, optional = true }

[features]
client = ["dep:tonic"]
server = ["dep:tonic"]

[dev-dependencies]
tempfile = { workspace = true }
which = { workspace = true }
