[package]
name = "astria-sequencer-validation"
version = "0.1.0"
edition = "2021"

[dependencies]
ct-merkle = { git = "https://github.com/rozbb/ct-merkle", rev = "a3f3965c368946944425d59370783b3381a1fb4d", features = ["serde"] }

bytes = { workspace = true }
eyre = { workspace = true }
hex = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tendermint = { workspace = true }
