replicaCount: 1

# this image is overridden in ci/cd with the image built in ci/cd
bridgeTesterUtilityImage: ghcr.io/astriaorg/bridge-tester-utility:local

imagePullSecrets: []
nameOverride: ""
namespaceOverride: ""
fullnameOverride: ""

# must match rollup name used in evm rollup chart values
evmRollupName: "astria"
# this is a shared dev address
evmToAddress: "0xaC21B97d35Bf75A7dAb16f35b111a50e78A72F30"
# evm execution api url
evmURL: "http://astria-evm-service.astria-dev-cluster.svc.cluster.local:8545"

sequencerURL: "http://node0-sequencer-rpc-service.astria-dev-cluster.svc.cluster.local:26657"
# must match chain id used in sequencer chart values
sequencerChainId: "sequencer-test-chain-0"
asset: "transfer/channel-0/utia"
feeAsset: "nria"

# sequencer bridge account. is funded during sequencer genesis.
bridgeAccount:
  address: "6f85297e587b61b37695a1ac17189b3e907e318e"
  bech32: "astria1d7zjjljc0dsmxa545xkpwxym86g8uvvwhtezcr"
  privkey: "6015fbe1c365d3c5ef92dc891db8c5bb26ad454bec2db4762b96e9f8b2430285"
  pubkey: "b78aa61c65f21e5fe0f31d221819053fa2286dd6eff83fc490e3ee746f144626"

celestiaChainID: "celestia-local-0"
celestiaNodeURL: "http://celestia-app-service.astria-dev-cluster.svc.cluster.local:26657"

# this account should be funded during celestia genesis
celestiaDevAccount:
  name: "dev-account"
  address: "celestia1m0ksdjl2p5nzhqy3p47fksv52at3ln885xvl96"
  mnemonic: "enrich avocado local net will avoid dizzy truth column excuse ready lesson"
