[package]
name = "sequencer-relayer"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.65"

[dependencies]
base64 = "0.21"
bech32 = "0.9"
dirs = "5.0"
ed25519-dalek = "1.0"
eyre = "0.6"
hex = "0.4"
prost = "0.11"
prost-types = "0.11"
rand = { version = "0.7", features = [ "getrandom" ] }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tendermint = "0.30"
tokio = { version = "1.24", features = [ "macros", "rt-multi-thread" ] }
tracing = "0.1"
tracing-subscriber = "0.2.15"
clap = { version = "4.1.9", features = ["derive"] }

[dependencies.rs-cnc]
git = "https://github.com/astriaorg/rs-cnc.git"
default-features = false
features = ["rustls"]

[build-dependencies]
prost-build = "0.11"

[dev-dependencies]
podman-api = "0.10.0"
uuid = { version = "1.3.1", features = ["v4"] }
tokio = { version = "1.24", features = [ "parking_lot", "sync", "time" ] }
askama = "0.12.0"
once_cell = "1.17.1"

[target.'cfg(target_os = "linux")'.dev-dependencies]
users = "0.11.0"
[target.'cfg(target_os = "macos")'.dev-dependencies]
home = "0.5.4"
