[package]
name = "astria-conductor-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.0"
once_cell = "1.17.1"
podman-api = "0.10.0"
tokio = { version = "1.28.0", features = ["sync"] }
uuid = { version = "1.3.2", features = ["v4"] }

[target.'cfg(target_os = "linux")'.dependencies]
users = "0.11.0"

[target.'cfg(target_os = "macos")'.dependencies]
home = "0.5.4"
